config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :users
  resources :products do
    resources :comments
  end
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]

  
  post 'payments/create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyNewApp</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  	<div class="container-fluid">
  	  <div class="navbar-header">
  	  	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" data-placement="bottom" title="Menu" id="hamburger">
  	  	  <span class="sr-only">Toggle navigation</span>
  	  	  <span class="icon-bar"></span>
  	  	  <span class="icon-bar"></span>
  	  	  <span class="icon-bar"></span>
  	  	</button> <!-- hamburger nav button -->
  	  	<div class="projectName navbar-brand">
  	  	  <%= link_to 'Kyle\'s App', static_pages_index_path %>
  	  	</div> <!-- projectName -->
  	  </div> <!-- navbar-header -->

      
  	  <div class="navbar-collapse collapse">
  	  	<%= form_tag("/products", method: "get", class: "navbar-form", role: "search") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag("Search", class: "btn btn-default") %>
          <% end %>
        <ul class="nav navbar-nav navbar-right">
          
  	  	  <li><%= link_to 'Specials', root_path %></li>
          <li><%= link_to 'Products Listing', products_path %></li>
  	      <li><%= link_to 'About', static_pages_about_path %></li>
  	      <li><%= link_to 'Contact', static_pages_contact_path %></li>
  	    </ul>
        <ul class="nav pull-right">
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
  	  </div> <!-- navbar-collapse -->

  	</div> <!-- container-fluid -->
  	
  </nav> <!-- end navbar -->
  <br>
  <br>
  <br>
  
  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-info"><%= alert %></p>
  <% end %>

  <%= yield %>
  <!-- equals sign makes the Ruby between the tags render the output as html, yield tells application where to render view files inside layout -->
  
  <br>
  <br>
  <footer>
  	

    <p>&copy; 2016 Kyle Antonini</p>
  	<a href="https://twitter.com/KyleAntonini" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @KyleAntonini</a>

    
  </footer>

</body>
</html>